import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = path.join(here, "albums.md");
const outputPath = path.join(here, "albums-data.js");
const raw = fs.readFileSync(sourcePath, "utf8").replaceAll("\r", "");
const lines = raw.split("\n");

const categories = [];
const albums = [];
let currentCategory = null;

function slugify(value) {
  return value
    .toLocaleLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

for (const [lineNumber, rawLine] of lines.entries()) {
  const line = rawLine.trim();
  if (!line || line === "SONICFIELD LIST") continue;

  if (!line.startsWith("- [")) {
    const categoryMatch = line.match(/^(.+?)(?:\s+—\s+(.+?))?\s+\((.+)\)$/);
    if (!categoryMatch) {
      throw new Error(`Unrecognized category line ${lineNumber + 1}: ${rawLine}`);
    }
    const group = categoryMatch[1].trim();
    const name = (categoryMatch[2] || categoryMatch[1]).trim();
    const description = categoryMatch[3].trim();
    currentCategory = {
      id: `room-${categories.length + 1}-${slugify(name)}`,
      index: categories.length,
      group,
      name,
      description
    };
    categories.push(currentCategory);
    continue;
  }

  const albumMatch = line.match(/^- \[([ xX])\]\s+(.+?)\s+\((\d{4})\)\s+—\s+(.+?)\s*$/);
  if (!albumMatch) {
    throw new Error(`Unrecognized album line ${lineNumber + 1}: ${rawLine}`);
  }
  if (!currentCategory) {
    throw new Error(`Album without a category on line ${lineNumber + 1}`);
  }
  albums.push({
    id: `album-${albums.length + 1}`,
    position: albums.length + 1,
    categoryId: currentCategory.id,
    title: albumMatch[2].trim(),
    year: Number(albumMatch[3]),
    artist: albumMatch[4].trim(),
    heard: /x/i.test(albumMatch[1])
  });
}

const data = {
  source: "albums.md",
  generatedAt: new Date().toISOString(),
  categories,
  albums
};

const output = `// Generated by build.mjs from albums.md. Do not edit by hand.\nwindow.SONICFIELD_DATA = ${JSON.stringify(data, null, 2)};\n`;
fs.writeFileSync(outputPath, output);

console.log(`Built ${albums.length} albums across ${categories.length} rooms -> ${path.basename(outputPath)}`);
